### PR TITLE
Babel 7 compatibility (Fixes #193)

### LINKED ISSUE #193: Doesn't work in v7.0.0-beta.3 due to a breaking change
Ref: [beta.3 removed .metadata properties](https://github.com/babel/babel/pull/6343).

### PR DESCRIPTION
**Pull request by jscinoz**
Fixes #193

Fixes compatibility with Babel 7, by using babel-helper-module-import's addDefault (instead of file.addImport, which is deprecated in Babel 7), and traversing the AST ourselves to find module imports, as Babel no longer does this for us.

Tests pass, and compatibility appears to be maintained with Babel 6.26.0, but I have not tested this extensively.

### CODE REVIEW

**Comment by jdalton** [comment]
Wow, thank you @jscinoz!

**Comment by tomchentw** [comment]
That was quick! Any chances we can get an npm release with a `beta` tag?

**Comment by jdalton** [comment]
It will most likely happen over the weekend.

**Comment by hallaathrad** [comment]
This was super quick work guys :raised_hands:
Any luck with that deployment yet? Wish I could help.

**Comment by spencerbeggs** [comment]
@jdalton Any chance you can cut a release for this? Tested locally it resolved the issue.

**Comment by jdalton** [comment]
v3.3.0 has been published :tada:

**Comment by sprinklr-gurgaon** [comment]
Which broke like this
`Error: Cannot find module 'babel-helper-module-imports'`

**Comment by abhinavsingi** [comment]
which broke like this
`Error: Cannot find module 'babel-helper-module-imports'`
